/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class in_p3d_mobile_P3dViewerJNIWrapper */

#ifndef _Included_in_p3d_mobile_P3dViewerJNIWrapper
#define _Included_in_p3d_mobile_P3dViewerJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_on_1surface_1created
  (JNIEnv *, jclass);

/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_on_1surface_1changed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass);

/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    init_asset_manager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_init_1asset_1manager
  (JNIEnv *, jclass, jobject);

/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    load_binary
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_load_1binary
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    start_rotate_cam
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_start_1rotate_1cam
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    rotate_cam
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_rotate_1cam
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     in_p3d_mobile_P3dViewerJNIWrapper
 * Method:    reset_cam
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_in_p3d_mobile_P3dViewerJNIWrapper_reset_1cam
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
